image: maven:3.8.3-jdk-11
 
stages:
  - build
  - test

compile_eclipse_plugin:
  tags:
   - docker
  stage: build
  script:
    - echo "Compiling Eclipse Plugin"
    - mvn clean verify -B -DskipTests
  only:
    - ci

compile_maven_plugin:
  tags:
    - docker 
  stage: build
  script:
    - echo "Compiling Maven Plugin"
    - |
      mvnCommand="clean install -DskipTests"
      dir('jsparrow-maven-plugin') {
        "${mvnBin()}" $mvnCommand
      }
  only:
    - ci

integration_tests:
  tags:
    - docker      
  stage: test
  script:
    - echo "Running Integration Tests"
    - |
      mvnCommand="clean verify -B -fae -Dsurefire.rerunFailingTestsCount=2"
      wrap([$class: 'Xvfb', additionalOptions: '', assignedLabels: '', autoDisplayName: true, debug: true, screen: '1366x768x24', shutdownWithBuild: true, timeout: 10]) {
        def statusCode = sh(returnStatus: true, script: "'${mvnBin()}' ${mvnCommand}")

        // In case of failing tests, there will be 'repeats' number of reruns
        int i = 0
        int repeats = 1
        while (statusCode != 0 && i < repeats) {
          def rerunTests = 'clean verify -B -fae'
          statusCode = sh(returnStatus: true, script: "'${mvnBin()}' ${rerunTests}")
          i = i + 1
        }

        setTestStatus(statusCode)

        // Collect unit test results
        junit '**/target/surefire-reports/TEST-*.xml'
        archive 'target/*.jar'
      }
  only:
    - ci