package at.splendit.simonykees.core.ui.preview;

import org.eclipse.compare.CompareViewerSwitchingPane;
import org.eclipse.jface.viewers.ISelectionChangedListener;
import org.eclipse.jface.viewers.IStructuredSelection;
import org.eclipse.jface.viewers.SelectionChangedEvent;
import org.eclipse.jface.viewers.TreeViewer;
import org.eclipse.ltk.core.refactoring.DocumentChange;
import org.eclipse.ltk.internal.ui.refactoring.TextEditChangePreviewViewer;
import org.eclipse.ltk.ui.refactoring.IChangePreviewViewer;
import org.eclipse.swt.SWT;
import org.eclipse.swt.custom.SashForm;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;

import at.splendit.simonykees.core.ui.AbstractWizardPage;

/**
 * The warning concerning restrictions is generated by a call to
 * {@link TextEditChangePreviewViewer}, which is an internal Eclipse class.
 * 
 * @author Ludwig Werzowa, Hannes Schweighofer, Andreja Sambolec
 * @since 0.9
 */
@SuppressWarnings("restriction")
public class RefactoringPreviewWizardPage extends AbstractWizardPage {

	private PreviewNode previewNode;
	private CompilationUnitNode currentCompilationUnitNode;
	private IChangePreviewViewer currentPreviewViewer;

	public RefactoringPreviewWizardPage(PreviewNode node) {
		super(node.getRule().getName());
		setTitle(node.getRule().getName());
		setDescription(node.getRule().getDescription());
		this.previewNode = node;

		this.currentCompilationUnitNode = new CompilationUnitNode(
				previewNode.getDocumentChanges().keySet().stream().findFirst().orElse(null));
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.eclipse.jface.dialogs.IDialogPage#createControl(org.eclipse.swt.
	 * widgets.Composite)
	 */
	@Override
	public void createControl(Composite parent) {
		Composite container = new Composite(parent, SWT.NONE);

		GridLayout layout = new GridLayout();

		// margin from TextEditChangePreviewViewer to Composite
		layout.marginHeight = 0;
		layout.marginWidth = 0;

		// without setting the layout, nothing displays
		container.setLayout(layout);

		setControl(container);

		SashForm sashForm = new SashForm(container, SWT.VERTICAL);

		createFileView(sashForm);
		createPreviewViewer(sashForm);
		
		/*
		 * sets height relation between children to be 1:3 
		 * when it has two children
		 */
		sashForm.setWeights(new int[] {1, 3});
	    
	}

	private void createFileView(Composite parent) {
		TreeViewer treeViewer = new TreeViewer(parent);
		CompilationUnitContentProvider contentProvider = new CompilationUnitContentProvider();

		treeViewer.setContentProvider(contentProvider);
		treeViewer.addSelectionChangedListener(createSelectionChangedListener());
		treeViewer.setInput(previewNode.getDocumentChanges().keySet());
		
	}

	private void createPreviewViewer(Composite parent) {

		// GridData works with GridLayout
		GridData gridData = new GridData(GridData.FILL_BOTH);
		parent.setLayoutData(gridData);

		currentPreviewViewer = new TextEditChangePreviewViewer();
		currentPreviewViewer.createControl(parent);
		
		populatePreviewViewer();
				
	}

	private ISelectionChangedListener createSelectionChangedListener() {
		return new ISelectionChangedListener() {
			@Override
			public void selectionChanged(SelectionChangedEvent event) {
				IStructuredSelection sel = (IStructuredSelection) event.getSelection();

				if (sel.size() == 1) {
					CompilationUnitNode newSelection = (CompilationUnitNode) sel.getFirstElement();
					if (!newSelection.equals(currentCompilationUnitNode)) {
						currentCompilationUnitNode = newSelection;
						populatePreviewViewer();
					}
				}
			}
		};
	}

	private void populatePreviewViewer() {
		currentPreviewViewer.setInput(TextEditChangePreviewViewer.createInput(getCurrentDocumentChange()));
		((CompareViewerSwitchingPane) currentPreviewViewer.getControl())
				.setTitleArgument(currentCompilationUnitNode.getClassName());
	}

	private DocumentChange getCurrentDocumentChange() {
		return previewNode.getDocumentChanges().get(currentCompilationUnitNode.getCompilationUnit());
	}

}
