package at.splendit.simonykees.core.ui;

import org.eclipse.compare.CompareViewerSwitchingPane;
import org.eclipse.jdt.core.dom.ASTVisitor;
import org.eclipse.jface.viewers.ISelectionChangedListener;
import org.eclipse.jface.viewers.IStructuredSelection;
import org.eclipse.jface.viewers.SelectionChangedEvent;
import org.eclipse.jface.viewers.TreeViewer;
import org.eclipse.ltk.core.refactoring.DocumentChange;
import org.eclipse.ltk.internal.ui.refactoring.TextEditChangePreviewViewer;
import org.eclipse.ltk.ui.refactoring.IChangePreviewViewer;
import org.eclipse.swt.SWT;
import org.eclipse.swt.custom.SashForm;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;

import at.splendit.simonykees.core.rule.RefactoringRule;

/**
 * The warning concerning restrictions is generated by a call to
 * {@link TextEditChangePreviewViewer}, which is an internal Eclipse class.
 * 
 * @author Ludwig Werzowa, Hannes Schweighofer
 * @since 0.9
 */
@SuppressWarnings("restriction")
public class RefactoringPreviewWizardPage extends AbstractWizardPage {

	private RefactoringRule<? extends ASTVisitor> refactoringRule;
	private CompilationUnitNode currentCompilationUnitNode;
	private IChangePreviewViewer currentPreviewViewer;

	public RefactoringPreviewWizardPage(RefactoringRule<? extends ASTVisitor> rule) {
		super(rule.getName());
		setTitle(rule.getName());
		setDescription(rule.getDescription());
		this.refactoringRule = rule;

		this.currentCompilationUnitNode = new CompilationUnitNode(
				refactoringRule.getDocumentChanges().keySet().stream().findFirst().orElse(null));
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.eclipse.jface.dialogs.IDialogPage#createControl(org.eclipse.swt.
	 * widgets.Composite)
	 */
	@Override
	public void createControl(Composite parent) {
		Composite container = new Composite(parent, SWT.NONE);

		GridLayout layout = new GridLayout();

		// margin from TextEditChangePreviewViewer to Composite
		layout.marginHeight = 0;
		layout.marginWidth = 0;

		// without setting the layout, nothing displays
		container.setLayout(layout);

		setControl(container);

		SashForm sashForm = new SashForm(container, SWT.VERTICAL);

		createFileView(sashForm);
		createPreviewViewer(sashForm);
	}

	private void createFileView(Composite parent) {
		TreeViewer treeViewer = new TreeViewer(parent);
		CompilationUnitContentProvider contentProvider = new CompilationUnitContentProvider();

		treeViewer.setContentProvider(contentProvider);
		treeViewer.addSelectionChangedListener(createSelectionChangedListener());
		treeViewer.setInput(refactoringRule.getDocumentChanges().keySet());
	}

	private void createPreviewViewer(Composite parent) {

		// GridData works with GridLayout
		GridData gridData = new GridData(GridData.FILL_BOTH);
		parent.setLayoutData(gridData);

		currentPreviewViewer = new TextEditChangePreviewViewer();
		currentPreviewViewer.createControl(parent);

		populatePreviewViewer();
	}

	private ISelectionChangedListener createSelectionChangedListener() {
		return new ISelectionChangedListener() {
			@Override
			public void selectionChanged(SelectionChangedEvent event) {
				IStructuredSelection sel = (IStructuredSelection) event.getSelection();

				if (sel.size() == 1) {
					CompilationUnitNode newSelection = (CompilationUnitNode) sel.getFirstElement();
					if (!newSelection.equals(currentCompilationUnitNode)) {
						currentCompilationUnitNode = newSelection;
						populatePreviewViewer();
					}
				}
			}
		};
	}

	private void populatePreviewViewer() {
		currentPreviewViewer.setInput(TextEditChangePreviewViewer.createInput(getCurrentDocumentChange()));
		((CompareViewerSwitchingPane) currentPreviewViewer.getControl())
				.setTitleArgument(currentCompilationUnitNode.getClassName());
	}

	private DocumentChange getCurrentDocumentChange() {
		return refactoringRule.getDocumentChanges().get(currentCompilationUnitNode.getCompilationUnit());
	}

}
