package eu.jsparrow.license.netlicensing.validation.impl;

/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Using mvn-copy this file is replaced with the contents of one of the files in 
 * 'main/config-files'. If you need to make changes, make them there. 
 */
@SuppressWarnings("nls")
public class NetlicensingProperties {

	private NetlicensingProperties() {
	}

	static final String LICENSE_ENVIRONMENT = "Test";
	static final String LICENSE_PRODUCT_NUMBER = "PZ9HF95UJ";
	static final String API_KEY = "bf7f1092-3c88-492f-8a52-d00823d225a8";
	static final String FLOATING_PRODUCT_MODULE_NUMBER = "MXVUFV9RN";
	static final String PRODUCT_NUMBER = "PZ9HF95UJ";
}