package eu.jsparrow.license.netlicensing.validation.impl;

/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Using mvn-copy this file is replaced with the contents of one of the files in 
 * 'main/config-files'. If you need to make changes, make them there. 
 */
@SuppressWarnings("nls")
public class NetlicensingProperties {

	private NetlicensingProperties() {
	}

	static final String API_KEY = "bf7f1092-3c88-492f-8a52-d00823d225a8";
}